# Generated by Django 2.0.8 on 2018-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180503_1926'),
    ]

    database_operations = [

    ]

    state_operations = [
        migrations.RemoveField(
            model_name='tag',
            name='values',
        ),
        migrations.AlterField(
            model_name='valuestotag',
            name='raw_data_source',
            field=models.IntegerField(),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations = database_operations, 
            state_operations = state_operations)
    ]
