# Generated by Django 2.0.8 on 2018-11-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('importer', '0003_auto_20180920_1828'),
    ]

    database_operations = [
        migrations.AlterModelTable('RawDataSource', 'core_rawdatasource')
    ]

    state_operations = [
        migrations.DeleteModel('RawDataSource')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
